apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-NOM PRENOM-MonApplication-frontend-ingress
  namespace: dev-NOM PRENOM-MonApplication-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dev.monsousdomain.flapi.org
      secretName: dev-NOM PRENOM-MonApplication-frontend-tls
  rules:
    - host: dev.monsousdomain.flapi.org
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: dev-NOM PRENOM-MonApplication-frontend-service
                port:
                  number: 3000
