apiVersion: v1
kind: Service
metadata:
  name: dev-NOM PRENOM-MonApplication-frontend-service
  namespace: dev-NOM PRENOM-MonApplication-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: dev-NOM PRENOM-MonApplication-frontend
