apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-NOM PRENOM-MonApplication-frontend-cert
  namespace: prod-NOM PRENOM-MonApplication-frontend
spec:
  secretName: prod-NOM PRENOM-MonApplication-frontend-tls
  dnsNames:
    - monsousdomain.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
